name: Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install npm dependencies
        run: npm install

      - name: Copy .env.testing
        run: cp .env.testing .env

      - name: Generate application key
        run: php artisan key:generate --no-interaction

      - name: Build Laravel
        run: php artisan test

      - name: Build Vue.js application
        run: npm run build

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/composer.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
